server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Logs da aplicação SkyHAL
  - job_name: skyhal-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: skyhal-api
          __path__: /var/log/skyhal/*.log

    pipeline_stages:
      # Parse de logs JSON estruturados
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            trace_id: trace_id
            span_id: span_id
            user_id: user_id
            request_id: request_id
            component: component

      # Extração de labels
      - labels:
          level:
          trace_id:
          component:

      # Timestamp parsing
      - timestamp:
          source: timestamp
          format: RFC3339

  # Logs do sistema
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log

    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\S+\s+\S+\s+\S+)\s+(?P<hostname>\S+)\s+(?P<service>\S+):\s+(?P<message>.*)'
      - labels:
          hostname:
          service:
      - timestamp:
          source: timestamp
          format: Jan 02 15:04:05

  # Logs de containers Docker (se disponível)
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'log_stream'

    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            message: log
      - timestamp:
          source: timestamp
          format: RFC3339Nano
