version: '3.8'

services:
  # Prometheus - Métricas
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: skyhal-prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - skyhal-observability

  # Jaeger - Tracing Distribuído
  jaeger:
    image: jaegertracing/all-in-one:1.49
    container_name: skyhal-jaeger
    ports:
      - "16686:16686"  # UI
      - "14268:14268"  # HTTP collector
      - "14250:14250"  # gRPC collector
      - "6831:6831/udp"  # UDP collector
      - "6832:6832/udp"  # UDP collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    volumes:
      - jaeger_data:/tmp
    networks:
      - skyhal-observability

  # Loki - Logs
  loki:
    image: grafana/loki:2.9.0
    container_name: skyhal-loki
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - skyhal-observability

  # Promtail - Log Collector
  promtail:
    image: grafana/promtail:2.9.0
    container_name: skyhal-promtail
    volumes:
      - /var/log:/var/log:ro
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - skyhal-observability

  # Grafana - Visualização
  grafana:
    image: grafana/grafana:10.1.0
    container_name: skyhal-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - jaeger
      - loki
    networks:
      - skyhal-observability

  # OTEL Collector - Centralizador de telemetria
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.85.0
    container_name: skyhal-otel-collector
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter metrics
    volumes:
      - ./otel/otel-collector-config.yml:/etc/otelcol-contrib/otel-collector-config.yml
    command: ["--config=/etc/otelcol-contrib/otel-collector-config.yml"]
    depends_on:
      - prometheus
      - jaeger
    networks:
      - skyhal-observability

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  loki_data:
    driver: local
  jaeger_data:
    driver: local

networks:
  skyhal-observability:
    driver: bridge
    name: skyhal-observability
